### ISSUE TITLE
Code and Presented Results conflicts 

### ISSUE THREAD

**Issue by wangmiaowei** [TEXTurePaper/TEXTurePaper#12]
Thanks for your contributions. However, when I use your code for Napoleon I get the ghost face in the back of people:

 
![Screenshot from 2023-04-03 21-41-32](https://user-images.githubusercontent.com/27915265/229527507-e4c3b9c7-406c-4760-b9a8-fe800f4b9bcd.png)
And I found it is due to the generated map by the diffusion model:
![Screenshot from 2023-04-03 21-48-31](https://user-images.githubusercontent.com/27915265/229529190-67459a3a-6e6f-488c-84d0-7a325bfeff2a.png)

However, in your project presentation web, it seems your generated mesh is good. Could you explain the differences? Well, I think it is really an interesting problem and will become the core thing for 3DAIGC using 2D diffusion.

**Comment by eladrich** [comment]
These kind of artifacts usually happen due to the diffusion process not being sensitive enough to the viewpoint defined in the prompt, as discussed in several previous text-to-3D papers.

While we don't see it as often in TEXTure, remember that the process is still stochastic so some artifacts will only happen on specific seeds, you can try running this prompt with several different seeds and see which one generates preferable results.
